[versions]
agp = "8.11.2"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
androidx-activity = "1.11.0"
androidx-appcompat = "1.7.1"
androidx-core = "1.17.0"
androidx-espresso = "3.7.0"
androidx-lifecycle = "2.9.5"
androidx-testExt = "1.3.0"
composeMultiplatform = "1.9.1"
junit = "4.13.2"
kotlin = "2.2.20"

navigationCompose = "2.9.1"
room = "2.8.2"
sqlite = "2.6.1"
ksp = "2.2.10-2.0.2"

# for ktor client
kotlinxCoroutineCore = "1.10.2"
ktorClientOkhttp = "3.3.1"
ktorClietLogging = "3.3.1"
kotlinxSerializationJson = "1.9.0"

#data store
datastore = "1.1.7"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-testExt-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-testExt" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }

androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-sqlite-wrapper = { module = "androidx.room:room-sqlite-wrapper", version.ref = "room" }
navigation-compose = {module="org.jetbrains.androidx.navigation:navigation-compose", version.ref="navigationCompose"}

#ktor implementation
kotlinx-coroutines-core = {module = "org.jetbrains.kotlinx:kotlinx-coroutines-core",version.ref = "kotlinxCoroutineCore"}
ktor-client-content-negotiation = {module = "io.ktor:ktor-client-content-negotiation",version.ref = "ktorClientOkhttp"}
ktor-client-logging = {module= "io.ktor:ktor-client-logging",version.ref = "ktorClietLogging"}
ktor-client-core = {module= "io.ktor:ktor-client-core",version.ref = "ktorClientOkhttp"}
ktor-client-darwin = {module= "io.ktor:ktor-client-darwin",version.ref = "ktorClientOkhttp"}
ktor-client-okhttp = {module= "io.ktor:ktor-client-okhttp",version.ref = "ktorClientOkhttp"}
ktor-serialization-kotlinx-json = {module= "io.ktor:ktor-serialization-kotlinx-json",version.ref = "ktorClientOkhttp"}
kotlinx-serialization-json  = {module= "org.jetbrains.kotlinx:kotlinx-serialization-json",version.ref = "kotlinxSerializationJson"}

#datastore implementation
androidx-datastore-core = {module = "androidx.datastore:datastore-core", version.ref = "datastore"}
androidx-datastore-preferences-core = {module = "androidx.datastore:datastore-preferences-core", version.ref = "datastore"}
[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
androidx-room = { id = "androidx.room", version.ref = "room" }